language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      compiler: gcc
    - os: osx
      compiler: clang
addons:
  apt:
    packages:
      - build-essential
      - cmake
      - zlib1g-dev
      - libfreetype6-dev
      - libopenal1
      - libopenal-dev
      - mesa-common-dev
      - libgl1-mesa-dev
      - libboost-dev
      - libsdl1.2-dev
      - libglew-dev
      - libqt4-dev
      - libcppunit-dev
      - libglm-dev
before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ] ; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = osx ] ; then brew upgrade cmake boost ; fi
  - if [ "$TRAVIS_OS_NAME" = osx ] ; then brew install zlib freetype sdl2 libepoxy qt5 cppunit glm ; fi
script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -Werror=dev -Werror=deprecated -DCONTINUOUS_INTEGRATION=1 -DICON_TYPE=none
  - make -j1
  - make check
branches:
  only:
    - master
    - travis
notifications:
  irc:
    channels:
      - "irc.freenode.net#arxfatalis"
    on_success: change
    on_failure: always
