language: cpp
compiler:
  - gcc
before_install:
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install build-essential cmake zlib1g-dev libfreetype6-dev libopenal1 libopenal-dev mesa-common-dev libgl1-mesa-dev libboost-dev libsdl1.2-dev libglew-dev qt-sdk libglm-dev
script: mkdir build && cd build && cmake .. && make -j1
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.freenode.net#arxfatalis"
    on_success: change
    on_failure: always
